name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/coinbase-sandbox:latest
            ghcr.io/${{ env.REPO_OWNER }}/coinbase-sandbox:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/coinbase-sandbox:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/coinbase-sandbox:buildcache,mode=max

#      - name: Run Tests
#        run: dotnet test